### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yesod30** [1n0r1/monster-siren-download#1]
I tried running the python script, it starts downloading and completes for a bunch of album and songs, until it crash with the following error of FileNotFound:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\Desktop\video musica immagini\monster-siren-download-main\main.py", line 186, in download_album
    filename, filetype = download_song(session=session, directory=directory + album_name, name=song_name, url=song_sourceUrl)
  File "D:\Desktop\video musica immagini\monster-siren-download-main\main.py", line 121, in download_song
    AudioSegment.from_wav(filename).export(directory + '/' + make_valid(name) + '.flac', format='flac')
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\audio_segment.py", line 963, in export
    p = subprocess.Popen(conversion_command, stdin=devnull, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Desktop\video musica immagini\monster-siren-download-main\main.py", line 233, in <module>
    main()
  File "D:\Desktop\video musica immagini\monster-siren-download-main\main.py", line 225, in main
    pool.map(download_album, albums)
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Samuele\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
```

I added some logging, and this is the list of the last 50 album/songs downloaded, before the crash
```
INFO:root:Current song Reversed time
INFO:root:Current album LITHOS
INFO:root:Current song LITHOS
INFO:root:Current album Sparkling Hydraulics
INFO:root:Current song Everything's Alright (Instrumental)
INFO:root:Current album Lullabye
INFO:root:Current song Sparkling Hydraulics
INFO:root:Current song Lullabye
INFO:root:Current album 独行长路
INFO:root:Current album Requiem
INFO:root:Current song Lullabye (Instrumental)
INFO:root:Current song Requiem
INFO:root:Current song 独行长路
INFO:root:Current album CONFRONT
INFO:root:Current song CONFRONT
INFO:root:Current song Requiem (Instrumental)
INFO:root:Current album 示岁
INFO:root:Current song 示岁
INFO:root:Current album Renegade
INFO:root:Current song Renegade
INFO:root:Current album Boiling Blood
INFO:root:Current song Boiling Blood
INFO:root:Current song Renegade (Instrumental)
INFO:root:Current song Boiling Blood (Instrumental)
INFO:root:Current album Curtain Call
INFO:root:Current song Curtain Call
INFO:root:Current album Zone 10⁻⁸
INFO:root:Current song Zone 10⁻⁸
INFO:root:Current album 春弦
INFO:root:Current album Speed of Light
INFO:root:Current song 春弦
INFO:root:Current song Speed of Light
INFO:root:Current album 故乡的风
INFO:root:Current song 故乡的风
INFO:root:Current song Speed of Light (Instrumental)
INFO:root:Current album Operation Barrenland
INFO:root:Current album 火蓝之心原声带
INFO:root:Current song Operation Barrenland (W&W Soundtrack Mix)
INFO:root:Current song Aflame Avenue
INFO:root:Current song Not Your Business
INFO:root:Current song Ready？
INFO:root:Current album 明日方舟OST1
INFO:root:Current song Synthetech
INFO:root:Current song 逃亡part2
INFO:root:Current song 生命流
INFO:root:Current song 泛用型自动化解决方案0.3.2.9f2
INFO:root:Current song 人性
INFO:root:Current song 短兵相接
INFO:root:Current song 大柏墟
INFO:root:Current song 终局抵抗者
INFO:root:Current song 血液
INFO:root:Current song 执棋者之骨
INFO:root:Current song 永冻症
INFO:root:Current song 旅途前方
```

**Comment by yesod30** [comment]
Nevermind, it seems the issue was a wrong path for the ffmpeg library in the PATH variables

**Comment by 1n0r1** [comment]
Thanks for opening the issue. I will add space character to blacklist as well (trailing space for an album name is questionable though).

Just updated the code and can you please try it to see if it works for you? I will replicate the issue on my end when I got the time and see if the code fix it.

**Comment by yesod30** [comment]
No it doesn't work. from what i could see from your last commit, you added the space character to the blacklist, but you use it only for the song name, not the album name. The issue is that the album is called "The cure " (notice the space after cure). I assume it was a mistake on HG part, but this does make the script crash with a FileNotFound, since on windows the folder would be calle "The cure", without the space. 
I would suggest just calling .strip() on both album and song name, so it automatically removes possible trailing and leading whitespaces. So having row 136 being `album_name = args['name'].strip()` and row 171 being `song_name = song['name'].strip()`

**Comment by 1n0r1** [comment]
I realized the blacklist only applies to song name (been a while since I last look at the code), so in the newest commit I apply blacklist to album name as well. Let me know if that works for you!

**Comment by 1n0r1** [comment]
Replicated the error on Windows and fixed the error in the latest commit.

**Comment by tmprnc** [comment]
It seems like this error is back.

Not sure if this is specifically the same reason; but the error log is very similar.

```
Skipping downloaded album 探索者的银凇止境OST
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\msr-download\main.py", line 187, in download_album
    filename, filetype = download_song(session=session, directory=directory + make_valid(album_name), name=song_name, url=song_sourceUrl)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\msr-download\main.py", line 122, in download_song
    AudioSegment.from_wav(filename).export(directory + '/' + make_valid(name) + '.flac', format='flac')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Temperance\msr-download\main.py", line 234, in <module>
    main()
  File "C:\Users\Temperance\msr-download\main.py", line 226, in main
    pool.map(download_album, albums)
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by 1n0r1** [comment]
> It seems like this error is back.
> 
> Not sure if this is specifically the same reason; but the error log is very similar.
> 
> ```
> Skipping downloaded album 探索者的银凇止境OST
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>                     ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
>     return list(map(*args))
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\msr-download\main.py", line 187, in download_album
>     filename, filetype = download_song(session=session, directory=directory + make_valid(album_name), name=song_name, url=song_sourceUrl)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\msr-download\main.py", line 122, in download_song
>     AudioSegment.from_wav(filename).export(directory + '/' + make_valid(name) + '.flac', format='flac')
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\audio_segment.py", line 808, in from_wav
>     return cls.from_file(file, 'wav', parameters=parameters)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
>     info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
>     res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\Temperance\msr-download\main.py", line 234, in <module>
>     main()
>   File "C:\Users\Temperance\msr-download\main.py", line 226, in main
>     pool.map(download_album, albums)
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 367, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Temperance\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 774, in get
>     raise self._value
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```

Thank you, I replicated the problem and will look into it. Probably a weird album name messing with the file directory.

**Comment by 1n0r1** [comment]
@tmprnc nvm I believe the problem is ffmpeg is not installed or not found in your path. Check if you can simply run `ffmpeg` in a terminal or not to verify if it is installed.

**Comment by tmprnc** [comment]
> @tmprnc nvm I believe the problem is ffmpeg is not installed or not found in your path. Check if you can simply run `ffmpeg` in a terminal or not to verify if it is installed.

![1706798709](https://github.com/1n0r1/monster-siren-download/assets/3785923/3f363c58-bd13-43b3-bc2b-b9e704ab20e9)
I can confirm ffmpeg is in PATH.

**Comment by 1n0r1** [comment]
> > @tmprnc nvm I believe the problem is ffmpeg is not installed or not found in your path. Check if you can simply run `ffmpeg` in a terminal or not to verify if it is installed.
> 
> ![1706798709](https://github.com/1n0r1/monster-siren-download/assets/3785923/3f363c58-bd13-43b3-bc2b-b9e704ab20e9)
> I can confirm ffmpeg is in PATH.

When you run script, does the log output any warning about ffmpeg not found? Additionally, check whether the wav file is downloaded or if the script has permission to access the file.

**Comment by tmprnc** [comment]
I'm not entirely sure what happened, but while trying to find different avenues to fix it (I've tried updating ffmpeg to the latest build via winget; and I ran the script via all versions of the Python executable I could find, with 3.10 working for the most part.
Just now I have ran it again with the default Python.exe and it seems that all but one album had been successfully downloaded in that previous attempt. 
![1706811501](https://github.com/1n0r1/monster-siren-download/assets/3785923/c06c6e71-87e2-46be-a329-7885dadcff8c)

Not entirely sure what happened here, maybe ffmpeg version? But the previous one used to work, and it's not like I had downloaded an update to the script that would have broken compatibility.

**Comment by 1n0r1** [comment]
> I'm not entirely sure what happened, but while trying to find different avenues to fix it (I've tried updating ffmpeg to the latest build via winget; and I ran the script via all versions of the Python executable I could find, with 3.10 working for the most part.
> Just now I have ran it again with the default Python.exe and it seems that all but one album had been successfully downloaded in that previous attempt. 
> ![1706811501](https://github.com/1n0r1/monster-siren-download/assets/3785923/c06c6e71-87e2-46be-a329-7885dadcff8c)
> 
> Not entirely sure what happened here, maybe ffmpeg version? But the previous one used to work, and it's not like I had downloaded an update to the script that would have broken compatibility.

Seems like it ran without a problem this time? Maybe verify if the album is completely downloaded/converted, but other than that, the ffmpeg problem seems to have resolved itself?
