### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'disable'

### ISSUE THREAD

**Issue by xht8723** [1n0r1/monster-siren-download#4]
```
AttributeError: 'tqdm' object has no attribute 'disable'
Exception ignored in: <function tqdm.__del__ at 0x0000016DB304C7C0>
Traceback (most recent call last):
  File "C:\Users\xht87\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\_tqdm.py", line 764, in __del__
    self.close()
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\xht87\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xht87\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "F:\softwares\monster-siren-download-main\main.py", line 187, in download_album
    filename, filetype = download_song(session=session, directory=directory + make_valid(album_name), name=song_name, url=song_sourceUrl)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\softwares\monster-siren-download-main\main.py", line 109, in download_song
    with open(filename, 'w+b') as f, tqdm(
                                     ^^^^^
  File "C:\Users\xht87\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\_tqdm.py", line 383, in __new__
    cls.monitor = TMonitor(cls, cls.monitor_interval)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xht87\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\_tqdm.py", line 68, in __init__
    getattr(sys, 'setcheckinterval'))(100)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute 'setcheckinterval'
```

It seems just a tqdm error caused all this.
I've never used tqdm so im not sure, but I removed tqdm bar it seems working fine.

**Comment by 1n0r1** [comment]
Thanks for making the issue. What is your current tqdm version? tqdm released a new version recently so maybe that broke the code? Have you try downgrading tqdm to 4.66.0?
I can try to see if I can replicate the issue.

**Comment by xht8723** [comment]
> Thanks for making the issue. What is your current tqdm version? tqdm released a new version recently so maybe that broke the code? Have you try downgrading tqdm to 4.66.0? I can try to see if I can replicate the issue.

It's my bad....just upgraded tqdm and it's working fine now.
Never used tqdm but apparently I somehow installed them long time ago.

Thanks for this script btw! Metadata extraction is the cherry on the top!

**Comment by 1n0r1** [comment]
> > Thanks for making the issue. What is your current tqdm version? tqdm released a new version recently so maybe that broke the code? Have you try downgrading tqdm to 4.66.0? I can try to see if I can replicate the issue.
> 
> It's my bad....just upgraded tqdm and it's working fine now. Never used tqdm but apparently I somehow installed them long time ago.
> 
> Thanks for this script btw! Metadata extraction is the cherry on the top!
@xht8723 Thank you, glad it works for you!
